<a href="https://colab.research.google.com/github/jungeun919/Pytorch_study/blob/main/Pytorch_Tutorial/1.6Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor

- numpy의 ndarray와 유사
- GPU를 사용한 연산 가속 가능

In [1]:
from __future__ import print_function
import torch

# 초기화되지 않은 5x3 행렬
x = torch.empty(5, 3)
print(x)

tensor([[1.4057e+33, 3.0753e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0753e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 4.4908e+32]])


In [2]:
# 무작위로 초기화된 행렬
x = torch.rand(5, 3)
print(x)

tensor([[0.2869, 0.6917, 0.5935],
        [0.0661, 0.8180, 0.0479],
        [0.1911, 0.2763, 0.1364],
        [0.6780, 0.8408, 0.5226],
        [0.1736, 0.3055, 0.2187]])


In [3]:
# 0으로 채워진 행렬
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
# 데이터로부터 tensor를 직접 생성
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
# new_* 메소드는 크기를 받음
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

# dtype을 오버라이트함, 결과는 동일한 크기
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.5108,  0.5379,  0.0042],
        [-0.2641,  0.3770,  0.5977],
        [-2.1340,  0.6301, -0.4644],
        [ 0.7316, -0.6637,  0.5746],
        [-0.6569,  0.0916,  0.2427]])


In [6]:
# 행렬의 크기
print(x.size())

torch.Size([5, 3])


# 연산 (Operations)

In [7]:
# 덧셈
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[0.7624, 0.7752, 1.0940],
        [0.2289, 1.7971, 0.8011],
        [0.1394, 0.3479, 0.7950],
        [1.0153, 1.1867, 1.2389],
        [1.2079, 0.2673, 0.9827]])


In [8]:
print(torch.add(x, y))

tensor([[0.7624, 0.7752, 1.0940],
        [0.2289, 1.7971, 0.8011],
        [0.1394, 0.3479, 0.7950],
        [1.0153, 1.1867, 1.2389],
        [1.2079, 0.2673, 0.9827]])


In [9]:
# 결과(result) tensor를 인자로 제공
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.7624, 0.7752, 1.0940],
        [0.2289, 1.7971, 0.8011],
        [0.1394, 0.3479, 0.7950],
        [1.0153, 1.1867, 1.2389],
        [1.2079, 0.2673, 0.9827]])


In [10]:
# 바꿔치기(in-place) 방식으로 tensor의 값을 변경하는 연산 뒤에는 _가 붙음
# y에 x 더하기
y.add_(x)
print(y)

tensor([[0.7624, 0.7752, 1.0940],
        [0.2289, 1.7971, 0.8011],
        [0.1394, 0.3479, 0.7950],
        [1.0153, 1.1867, 1.2389],
        [1.2079, 0.2673, 0.9827]])


In [11]:
# 인덱스 표기 방법
print(x)
print(x[:, 1])

tensor([[0.6579, 0.0378, 0.4569],
        [0.1472, 0.9591, 0.6253],
        [0.0943, 0.3070, 0.1912],
        [0.3639, 0.9350, 0.3914],
        [0.4720, 0.1044, 0.8068]])
tensor([0.0378, 0.9591, 0.3070, 0.9350, 0.1044])


In [12]:
# 크기 변경
# tensor의 크기나 모양을 변경하고자 할 때 torch.view 사용
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
# tensor에 하나의 값만 존재한다면 .item()으로 숫자 값을 얻을 수 있음
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5748])
0.5748134255409241


# Torch Tensor를 Numpy 배열로 변환

- Torch Tensor가 CPU상에 있다면, Torch Tensor와 Numpy 배열은 메모리 공간을 공유함
- 하나를 변경하면 다른 하나도 변경됨

In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# Numpy 배열을 Torch Tensor로 변환

In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensor

- .to 메서드를 통해 Tensor를 어떠한 장치로도 이동 가능
- .to 메서드는 dtype도 변경 가능

In [18]:
# CUDA가 사용 가능한 환경에서만 실행
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)

    x = x.to(device)

    z = x + y
    print(z)
    print(z.to("cpu", torch.double))